# Generated by Django 5.2.9 on 2025-12-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinalVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('data_registro', models.DateField(verbose_name='Data do Registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais_vitais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
