# Generated by Django 5.2.9 on 2025-12-16 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
