# Generated by Django 5.2.9 on 2025-12-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('intensidade', models.CharField(choices=[('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Grave', 'Grave')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
        ),
    ]
